name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 添加您的構建和測試指令
    - name: Build and Test
      run: |
        echo "在這裡加入構建和測試的指令"

    # 如果有，添加部署步驟
    - name: Deploy
      run: |
        echo "在這裡加入部署的指令"
